# Generated by Django 4.1.6 on 2023-02-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="preco_entrada",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entradaproduto",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produto",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="requisicaosaidaproduto",
            name="status_requisicao",
            field=models.CharField(
                choices=[
                    ("cancelada", "Cancelada"),
                    ("aguardando_liberacao", "Aguardando Liberação"),
                    ("liberada", "Liberada"),
                    ("aguardando_compra", "Aguardando Compra"),
                    ("negada", "Negada"),
                ],
                max_length=25,
            ),
        ),
    ]
