# Generated by Django 4.1.6 on 2023-02-21 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_produto_preco_entrada_alter_entradaproduto_produto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaosaidaproduto",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requisicoes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requisicaosaidaproduto",
            name="status_requisicao",
            field=models.CharField(
                choices=[
                    ("aguardando_liberacao", "Aguardando Liberação"),
                    ("negada", "Negada"),
                    ("aguardando_compra", "Aguardando Compra"),
                    ("cancelada", "Cancelada"),
                    ("liberada", "Liberada"),
                ],
                default="aguardando_liberacao",
                max_length=25,
            ),
        ),
    ]
